# Generated by Django 6.0.1 on 2026-01-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
