# Generated by Django 6.0.1 on 2026-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
