# Generated by Django 6.0.1 on 2026-01-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
